Presentation/CNSMarketing.WEB/Areas/Manager/Controllers/AuthController.cs
using CNSMarketing.Application.Abstraction.ExternalService.Common;
using CNSMarketing.Application.Features.Command.AppUser.LoginUser;
using CNSMarketing.Application.Features.Command.AppUser.PasswordReset;
using CNSMarketing.Application.Features.Command.AppUser.RefreshTokenLogin;
using CNSMarketing.Application.Features.Command.AppUser.VerifyResetToken;
using CNSMarketing.Domain.Entity.Authentication;
using CNSMarketing.WEB.Const;
using MediatR;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace CNSMarketing.WEB.Areas.Manager.Controllers
{

    [Area("Manager")]
    public class AuthController : Controller
    {
        private readonly IMediator _mediator;
        private readonly IMailService _mailService;
        private readonly SignInManager<AppUser> _signInManager;
        private readonly UserManager<AppUser> _userManager;

        public AuthController(IMediator mediator, IMailService mailService, SignInManager<AppUser> signInManager, UserManager<AppUser> userManager)
        {
            _mediator = mediator;
            _mailService = mailService;
            _signInManager = signInManager;
            _userManager = userManager;
        }


        [AllowAnonymous]
        public IActionResult Login()
        {
            if (User.Identity!.IsAuthenticated)
            {
                return Redirect(ConstRoute.UserProfil);

            }

            return View();
        }


        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Login(LoginUserCommandRequest model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var response = await _mediator.Send(model);
            if (response.IsSuccess)
            {
                // Başarılı giriş durumunda, kullanıcıyı yönlendir
                return Redirect(ConstRoute.UserProfil);

            }

            ModelState.AddModelError(string.Empty, "Kullanıcı adı veya şifre hatalı.");
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> RefreshTokenLogin(RefreshTokenLoginCommandRequest model)
        {
            RefreshTokenLoginCommandResponse response = await _mediator.Send(model);
            if (response.IsSuccess)
            {
                return RedirectToAction("Index", "Home");
            }

            ModelState.AddModelError(string.Empty, response.Message);
            return View(model);
        }


        [HttpPost]
        public async Task<IActionResult> PasswordReset(PasswordResetCommandRequest model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var response = await _mediator.Send(model);
            if (response.IsSuccess)
            {
                // Şifre sıfırlama başarılıysa bir mesaj gösterebiliriz.
                ViewBag.Message = "Şifre sıfırlama bağlantısı e-posta adresinize gönderildi.";
            }
            else
            {
                ModelState.AddModelError(string.Empty, response.Message);
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> VerifyResetToken(VerifyResetTokenCommandRequest model)
        {
            VerifyResetTokenCommandResponse response = await _mediator.Send(model);
            if (response.IsSuccess)
            {
                // Token doğrulandıysa şifreyi sıfırlamak için kullanıcıyı yönlendirebiliriz.
                return RedirectToAction("ResetPassword");
            }

            ModelState.AddModelError(string.Empty, response.Message);
            return View(model);
        }

        [HttpGet]
        public IActionResult PasswordReset()
        {
            return View();
        }

        [HttpGet]
        public IActionResult VerifyResetToken()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Logout()
        {
            // Logout
            await HttpContext.SignOutAsync(IdentityConstants.ApplicationScheme);

            //Delete cookie
            Response.Cookies.Delete(".AspNetCore.Identity.Application");

            // Redirect to login page or home page
            return Redirect(ConstRoute.HomePage);
        }
    }
}

Presentation/CNSMarketing.WEB/Areas/Portal/Controllers/BlogsController.cs
using Microsoft.AspNetCore.Mvc;

namespace CNSMarketing.WEB.Areas.Portal.Controllers
{
    [Area("Portal")]
    public class BlogsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Presentation/CNSMarketing.WEB/Controllers/UsersController.cs
using CNSMarketing.Application.Abstraction.ExternalService.Common;
using CNSMarketing.Application.Abstraction.Service.UserRole;
using CNSMarketing.Application.Features.Command.AppUser.AssignRoleToUser;
using CNSMarketing.Application.Features.Command.AppUser.CreateUser;
using CNSMarketing.Application.Features.Command.AppUser.UpdatePassword;
using CNSMarketing.Application.Features.Queries.AppUser.GetAllUsers;
using CNSMarketing.Application.Features.Queries.AppUser.GetRolesToUser;
using CNSMarketing.Application.Features.Queries.Role.GetRoles;
using CNSMarketing.Application.Helpers;
using CNSMarketing.Application.Models.ViewModels.User;
using CNSMarketing.Domain.Entity.Authentication;
using CNSMarketing.WEB.Const;
using CNSMarketing.WEB.Filters;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace CNSMarketing.WEB.Controllers
{
    [DynamicAuthorization]
    public class UsersController : Controller
    {
        #region Fields & Ctor
        private readonly IMediator _mediator;
        private readonly IMailService _mailService;
        private readonly IUserService _userService;
        private readonly UserManager<AppUser> _userManager;

        public UsersController(IMediator mediator, IMailService mailService, IUserService userService, UserManager<AppUser> userManager)
        {
            _mediator = mediator;
            _mailService = mailService;
            _userService = userService;
            _userManager = userManager;
        }
        #endregion

        #region Methods

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Register()
        {
            if (User.Identity.IsAuthenticated)
            {
                return Redirect(ConstRoute.UserProfil);
            }
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> CreateUser(CreateUserCommandRequest createUserCommandRequest)
        {
            bool isUsernameUnique = await _userService.IsUsernameUniqueAsync(createUserCommandRequest.Username);
            bool isEmailUnique = await _userService.IsEmailUniqueAsync(createUserCommandRequest.Email);
            bool isPhoneNumberUnique = await _userService.IsPhoneNumberUniqueAsync(createUserCommandRequest.PhoneNumber);

            if (!isUsernameUnique)
            {
                ModelState.AddModelError("Username", "Kullanıcı adı zaten kullanımda.");
            }
            if (!isEmailUnique)
            {
                ModelState.AddModelError("Email", "E-posta adresi zaten kullanımda.");
            }
            if (!isPhoneNumberUnique)
            {
                ModelState.AddModelError("PhoneNumber", "Telefon numarası zaten kullanımda.");
            }

            if (ModelState.IsValid)
            {
                // Komutu işleyin
                var response = await _mediator.Send(createUserCommandRequest);

                if (response.IsSuccess)
                {
                    return RedirectToAction("Index", "Home");
                }

                // İşlem başarısızsa, hata mesajını ekleyin
                ModelState.AddModelError(string.Empty, response.Message);
            }

            // Model doğrulama veya işlem başarısızsa kayıt formunu tekrar göster
            return View("Register", createUserCommandRequest);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> UpdatePassword([FromBody] UpdatePasswordCommandRequest updatePasswordCommandRequest)
        {
            var response = await _mediator.Send(updatePasswordCommandRequest);
            return Ok(response);
        }


        [HttpGet] // TODO1
        [Authorize]
        public async Task<IActionResult> ConfirmEmail(string userId, string token)
        {
            var user = await _userManager.FindByIdAsync(userId);
            if (user == null)
                return BadRequest("Geçersiz kullanıcı.");

            var result = await _userManager.ConfirmEmailAsync(user, token);
            if (result.Succeeded)
            {
                TempData["message"] = "E-posta başarıyla doğrulandı!";
                return Redirect(ConstRoute.UserProfil);
            }

            return BadRequest("E-posta doğrulama işlemi başarısız.");
        }

        [HttpGet("get-confirm-email")] // TODO1
        public async Task<IActionResult> GetConfirmEmail()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return Json(new { success = false, message = "Kullanıcı bulunamadı." });
            }

            if (user.EmailConfirmed)
            {
                return Json(new { success = false, emailConfirmed = true, message = "E-posta zaten onaylanmış." });
            }

            // Kullanıcının son tıklama süresini kontrol edin (örneğin, bir CustomClaim veya başka bir veri kaynağı kullanarak)
            var lastSentTime = user.LastEmailSentTime; // Varsayım: Bu alanı eklediniz.
            if (lastSentTime != null && (DateTime.UtcNow - lastSentTime.Value).TotalSeconds < 60)
            {
                return Json(new { success = false, emailConfirmed = false, message = "E-postayı tekrar göndermek için 1 dakika bekleyin." });
            }

            // Email gönderim işlemi
            await _userService.GetConfirmEmailAsync(user);

            // Son gönderim zamanını güncelleyin
            user.LastEmailSentTime = DateTime.UtcNow;
            await _userManager.UpdateAsync(user);

            return Json(new { success = true, emailConfirmed = false, message = "Doğrulama e-postası gönderildi." });
        }



        [DynamicAuthorization] // TODO1
        [HttpGet]
        public async Task<IActionResult> GetAllUsers([FromQuery] GetAllUsersQueryRequest getAllUsersQueryRequest)
        {
            var response = await _mediator.Send(getAllUsersQueryRequest);

            return View(response);
        }


        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Profile()
        {
            var user = await _userManager.GetUserAsync(User);

            var profile = await _userService.GetUserProfileAsync(user);

            return View(profile);
        }

        public async Task<IActionResult> AssignRoleToUser()
        {

            // Eğer model geçerli değilse tekrar formu yükle
            var users = await _mediator.Send(new GetAllUsersQueryRequest());

            //var roles = await _mediator.Send(new GetRolesQueryRequest());

            var model = new AssignRoleViewModel
            {
                Users = users.Users.Select(x => new AppUser
                {
                    Id = x.Id,
                    UserName = x.UserName
                }).ToList(),

                //Roles = roles.Roles.Select(x => new AppRole
                //{
                //    Name = x.Name
                //}).ToList(),
            };



            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AssignRoleToUser(AssignRoleToUserCommandRequest model)
        {

            if (ModelState.IsValid)
            {
                var request = new AssignRoleToUserCommandRequest
                {
                    UserId = model.UserId,
                    Roles = model.Roles
                };

                var response = await _mediator.Send(model);

                TempData["SuccessMessage"] = "Rol başarılı bir şekilde atandı.";

                return Redirect(Request.Headers["Referer"].ToString());

            }

            TempData["Message"] = "Bir Problem Oluştu ";
            TempData["MessageType"] = "error";
            return Redirect(Request.Headers["Referer"].ToString());


            //return RedirectToAction("AssignRoleToUser");
            //}

            //var response = await _mediator.Send(assignRoleToUserCommandRequest);
            //return Ok(response);
        }



        [HttpGet("GetRolesToUser/{userId}")]
        public async Task<IActionResult> GetRolesToUser([FromRoute] string userId)
        {
            var response = await _mediator.Send(new GetRolesToUserQueryRequest { UserId = userId });
            return Ok(new { response.UserRoles });
        }


        [HttpGet("GetAllRoles")]
        public async Task<IActionResult> GetAllRoles()
        {
            var response = await _mediator.Send(new GetRolesQueryRequest());


            return Ok(response);
        }
        #endregion


        #region Check

        [HttpGet]
        public async Task<IActionResult> checkUsername(string username)
        {
            bool isUnique = await _userService.IsUsernameUniqueAsync(username);
            return Ok(isUnique);
        }

        [HttpGet]
        public async Task<IActionResult> checkEmail(string email)
        {
            bool isUnique = await _userService.IsEmailUniqueAsync(email);
            return Ok(isUnique);
        }

        [HttpGet]
        public async Task<IActionResult> checkPhone(string phone)
        {
            string cleanedPhone = ApplicationHelpers.CleanPhoneNumber(phone);

            bool isUnique = await _userService.IsPhoneNumberUniqueAsync(cleanedPhone);
            return Ok(isUnique);
        }

        #endregion
    }
}

Presentation/CNSMarketing.WEB/Views/Shared/LayoutPartial/_AppHeaderPartial.cshtml
<div class="hor-header header">
    <div class="container main-container">
        <div class="d-flex">
            <a aria-label="Hide Sidebar" class="app-sidebar__toggle" data-bs-toggle="sidebar"
               href="javascript:void(0)"></a>
            <!-- sidebar-toggle-->
            <a class="logo-horizontal" asp-controller="Home" asp-action="Index">
                <img src="~/assets/images/brand/logo-white.png" class="header-brand-img desktop-logo" alt="logo">
                <img src="~/assets/images/brand/logo-dark.png" class="header-brand-img light-logo1"
                     alt="logo">
            </a>
            <!-- LOGO -->
            <div class="d-flex order-lg-2 ms-auto header-right-icons">
                <button class="navbar-toggler navresponsive-toggler d-lg-none ms-auto" type="button"
                        data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent-4"
                        aria-controls="navbarSupportedContent-4" aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon fe fe-more-vertical"></span>
                </button>
                <div class="navbar navbar-collapse responsive-navbar p-0">
                    <div class="collapse navbar-collapse bg-white px-0" id="navbarSupportedContent-4">
                        <!-- SEARCH -->
                        <div class="header-nav-right p-5">
                            <a asp-controller="Users" asp-action="Register" class="btn ripple btn-min w-sm btn-outline-primary me-2 my-auto">
                               Register
                            </a>
                            <a asp-controller="Auth" asp-action="Login" asp-area="Manager" class="btn ripple btn-min w-sm btn-primary me-2 my-auto">
                                Login
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Presentation/CNSMarketing.WEB/Views/Shared/LayoutPartial/_HeadPartial.cshtml
@* <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" /> *@

<meta charset="UTF-8">
<meta name='viewport' content='width=device-width, initial-scale=1.0, user-scalable=0'>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="description" content="Sash – Bootstrap 5  Admin & Dashboard Template">
<meta name="author" content="Spruko Technologies Private Limited">
<meta name="keywords"
      content="admin,admin dashboard,admin panel,admin template,bootstrap,clean,dashboard,flat,jquery,modern,responsive,premium admin templates,responsive admin,ui,ui kit.">

<!-- FAVICON -->
<link rel="shortcut icon" type="image/x-icon" href="~/assets/images/brand/favicon.ico">

<!-- TITLE -->
<title>@ViewData["Title"] - CNS YAZILIM </title>


<!-- BOOTSTRAP CSS -->
<link id="style" href="~/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">

<!-- STYLE CSS -->
<link href="~/assets/css/style.css" rel="stylesheet">

<!-- Plugins CSS -->
<link href="~/assets/css/plugins.css" rel="stylesheet">

<!--- FONT-ICONS CSS -->
<link href="~/assets/css/icons.css" rel="stylesheet">

@* <!-- INTERNAL Switcher css -->
<link href="~/assets/switcher/css/switcher.css" rel="stylesheet">
<link href="~/assets/switcher/demo.css" rel="stylesheet"> *@

<link rel="stylesheet" href="~/CNSMarketing.WEB.styles.css" asp-append-version="true" />

Presentation/CNSMarketing.WEB/Views/Shared/LayoutPartial/_NavigationPartial.cshtml
@{
    var controller = ViewContext.RouteData.Values["controller"]?.ToString();
    var action = ViewContext.RouteData.Values["action"]?.ToString();
}


<div class="landing-top-header overflow-hidden">

    <div class="top sticky">
        <!--APP-SIDEBAR-->
        <div class="app-sidebar__overlay" data-bs-toggle="sidebar"></div>
        <div class="app-sidebar bg-transparent horizontal-main">
            <div class="container">
                <div class="row">
                    <div class="main-sidemenu navbar px-0">
                        <a class="navbar-brand ps-0 d-none d-lg-block" asp-controller="Home" asp-action="Index">
                            <img alt="" class="logo-2" src="~/assets/images/brand/logo-dark.png">
                            <img src="~/assets/images/brand/logo-white.png" class="logo-3" alt="logo">
                        </a>
                        <ul class="side-menu">
                            <li class="slide">
                                <a class="side-menu__item active" data-bs-toggle="slide" href="#home">
                                    <span class="side-menu__label">Home</span>
                                </a>
                            </li>

                            <li class="slide">
                                <a asp-controller="Seeder" asp-action="Index" >
                                    <span class="side-menu__label">Seeder</span>
                                </a>
                            </li>

                          @*    <a asp-controller="Users" asp-action="Register"
                               class="btn ripple btn-min w-sm btn-outline-primary me-2 my-auto d-lg-none d-xl-block d-block">
                                Register
                            </a> *@

                            <li class="slide">
                                <a class="side-menu__item" data-bs-toggle="slide" href="#Features">
                                    <span class="side-menu__label">Features</span>
                                </a>
                            </li>
                            <li class="slide">
                                <a class="side-menu__item" data-bs-toggle="slide" href="#About">
                                    <span class="side-menu__label">About</span>
                                </a>
                            </li>
                            <li class="slide">
                                <a class="side-menu__item" data-bs-toggle="slide" href="#Faqs">
                                    <span class="side-menu__label">Faq's</span>
                                </a>
                            </li>
                           @*  <li class="slide">
                                <a class="side-menu__item" data-bs-toggle="slide" href="#Blog">
                                    <span class="side-menu__label">Blog</span>
                                </a>
                            </li> *@
                            <li class="slide">
                                <a asp-area="Portal" asp-controller="Blogs" asp-action="Index">
                                    <span class="side-menu__label">Blog</span>
                                </a>
                            </li>

                            <li class="slide">
                                <a class="side-menu__item" data-bs-toggle="slide" href="#Clients">
                                    <span class="side-menu__label">Clients</span>
                                </a>
                            </li>
                            <li class="slide">
                                <a class="side-menu__item" data-bs-toggle="slide" href="#Contact">
                                    <span class="side-menu__label">Contact</span>
                                </a>
                            </li>
                            @* <li class="slide">
                                <a class="side-menu__item" data-bs-toggle="slide" href="javascript:void(0)">
                                    <span class="side-menu__label">Submenu items</span><i class="angle fe fe-chevron-right"></i>
                                </a>
                                <ul class="slide-menu">
                                    <li class="side-menu-label1">
                                        <a href="javascript:void(0)">
                                            Submenu
                                            items
                                        </a>
                                    </li>
                                    <li><a href="javascript:void(0)" class="slide-item">Submenu-1</a></li>
                                    <li class="sub-slide">
                                        <a class="sub-side-menu__item" data-bs-toggle="sub-slide" href="javascript:void(0)"><span class="sub-side-menu__label">Submenu-2</span><i class="sub-angle fe fe-chevron-right"></i></a>
                                        <ul class="sub-slide-menu">
                                            <li><a class="sub-slide-item" href="javascript:void(0)">Submenu-2.1</a></li>
                                            <li><a class="sub-slide-item" href="javascript:void(0)">Submenu-2.2</a></li>
                                            <li class="sub-slide2">
                                                <a class="sub-side-menu__item2" href="javascript:void(0)" data-bs-toggle="sub-slide2"><span class="sub-side-menu__label2">Submenu-2.3</span><i class="sub-angle2 fe fe-chevron-right"></i></a>
                                                <ul class="sub-slide-menu2">
                                                    <li><a href="javascript:void(0)" class="sub-slide-item2">Submenu-2.3.1</a></li>
                                                    <li><a href="javascript:void(0)" class="sub-slide-item2">Submenu-2.3.2</a></li>
                                                    <li><a href="javascript:void(0)" class="sub-slide-item2">Submenu-2.3.3</a></li>
                                                </ul>
                                            </li>
                                            <li><a class="sub-slide-item" href="javascript:void(0)">Submenu-2.4</a></li>
                                            <li><a class="sub-slide-item" href="javascript:void(0)">Submenu-2.5</a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </li> *@
                        </ul>
                        <div class="header-nav-right d-none d-lg-flex">

                            @if (User.Identity.IsAuthenticated)
                            {
                                <!-- Yönetim Sayfasına Yönlendirme Butonu -->
                                <a asp-controller="Manager" asp-action="Dashboard"
                                   class="btn ripple btn-min w-sm btn-success me-2 my-auto d-lg-none d-xl-block d-block">
                                    Yönetim Sayfası
                                </a>
                            }
                            else
                            {
                                <!-- Register ve Login Butonları -->
                                <a asp-controller="Users" asp-action="Register"
                                   class="btn ripple btn-min w-sm btn-outline-primary me-2 my-auto d-lg-none d-xl-block d-block">
                                    Register
                                </a>
                                <a asp-controller="Auth" asp-action="Login" asp-area="Manager"
                                   class="btn ripple btn-min w-sm btn-primary me-2 my-auto d-lg-none d-xl-block d-block">
                                    Login
                                </a>
                            }

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--/APP-SIDEBAR-->
    </div>

    @if (controller == "Home" && action == "Index")
    {
        <div class="demo-screen-headline main-demo main-demo-1 spacing-top overflow-hidden reveal" id="home">
            <div class="container px-sm-0">
                <div class="row">
                    <div class="col-xl-6 col-lg-6 mb-5 pb-5 animation-zidex pos-relative">
                        <h4 class="fw-semibold mt-7">Manage Your Business</h4>
                        <h1 class="text-start fw-bold">
                            We Help to Build Your Dream Project with <span class="text-primary animate-heading">Sash</span>
                        </h1>
                        <h6 class="pb-3">
                            Sash - Now you can use this admin template to design stunning dashboards
                            that will wow your target viewers or users to no end. To create a good and
                            well-structured dashboard,
                            you need to start from scratch with HTML, SCSS, CSS, and JS and with lots of coding,
                            but by using this Sash-Admin template.
                        </h6>

                        <a href="https://themeforest.net/item/sash-bootstrap-5-admin-dashboard-template/35183671"
                           target="_blank" class="btn ripple btn-min w-lg mb-3 me-2 btn-primary">
                            <i class="fe fe-play me-2"></i> Get Started
                        </a>
                        <a href="https://themeforest.net/user/spruko/portfolio"
                           class="btn ripple btn-min w-lg btn-outline-primary mb-3 me-2" target="_blank">
                            <i class="fe fe-eye me-2 d-inline-flex"></i>Discover More
                        </a>
                    </div>
                    <div class="col-xl-6 col-lg-6 my-auto">
                        <img src="~/assets/images/landing/2.png" alt="">
                    </div>
                </div>
            </div>
        </div>
    }

</div>

Presentation/CNSMarketing.WEB/Views/Shared/LayoutPartial/_ScriptsPartial.cshtml
<!-- JQUERY JS -->
<script src="~/assets/js/jquery.min.js"></script>

<!-- BOOTSTRAP JS -->
<script src="~/assets/plugins/bootstrap/js/popper.min.js"></script>
<script src="~/assets/plugins/bootstrap/js/bootstrap.min.js"></script>

<!-- COUNTERS JS-->
<script src="~/assets/plugins/counters/counterup.min.js"></script>
<script src="~/assets/plugins/counters/waypoints.min.js"></script>
<script src="~/assets/plugins/counters/counters-1.js"></script>

<!-- Perfect SCROLLBAR JS-->
<script src="~/assets/plugins/owl-carousel/owl.carousel.js"></script>
<script src="~/assets/plugins/company-slider/slider.js"></script>

<!-- Star Rating Js-->
<script src="~/assets/plugins/rating/jquery-rate-picker.js"></script>
<script src="~/assets/plugins/rating/rating-picker.js"></script>

<!-- Star Rating-1 Js-->
<script src="~/assets/plugins/ratings-2/jquery.star-rating.js"></script>
<script src="~/assets/plugins/ratings-2/star-rating.js"></script>

<!-- Sticky js -->
<script src="~/assets/js/sticky.js"></script>

<!-- CUSTOM JS -->
<script src="~/assets/js/landing.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>